<FOOD 테이블 creat>
  CREATE TABLE "TJOEUNIT"."DIET" 
   (   "IDX" NUMBER(*,0) NOT NULL , 
   "DIETFOODNAME" VARCHAR2(200 BYTE) NOT NULL , 
   "DIETKCAL" FLOAT(126) NOT NULL , 
   "DIETCARBS" FLOAT(126) NOT NULL , 
   "DIETPROTEIN" FLOAT(126) NOT NULL , 
   "DIETFAT" FLOAT(126) NOT NULL , 
   "DIETMEMO" VARCHAR2(2000 BYTE) NOT NULL , 
   "DIETPICTURE" VARCHAR2(1000 BYTE) DEFAULT 'no picture', 
   "DIETWRITEDATE" VARCHAR2(20 BYTE) DEFAULT sysdate NOT NULL , 
   "DIETWRITETIME" VARCHAR2(20 BYTE) DEFAULT sysdate NOT NULL , 
    CONSTRAINT "DIET_PK" PRIMARY KEY ("IDX")
  );

delete from food;
drop sequence food_idx_seq;
create sequence food_idx_seq;


insert into food (idx, foodname, kcal, carbs, protein, fat) 
values (freeboard_idx_seq.nextval, 'ȸ', 123, 24, 124 , 12);
commit;
 
  
 <DIET 테이블 creat>
    CREATE TABLE "DIET" 
   (   "IDX" NUMBER(*,0) NOT NULL , 
   "DIETFOODNAME" VARCHAR2(200 BYTE) NOT NULL , 
   "DIETKCAL" FLOAT(126) NOT NULL , 
   "DIETCARBS" FLOAT(126) NOT NULL , 
   "DIETPROTEIN" FLOAT(126) NOT NULL , 
   "DIETFAT" FLOAT(126) NOT NULL , 
   "DIETMEMO" VARCHAR2(2000 BYTE) NOT NULL , 
   "DIETPICTURE" VARCHAR2(1000 BYTE) DEFAULT 'no picture', 
   "DIETWRITEDATE" VARCHAR2(20 BYTE) DEFAULT sysdate NOT NULL , 
   "DIETWRITETIME" VARCHAR2(20 BYTE) DEFAULT sysdate NOT NULL , 
    CONSTRAINT "DIET_PK" PRIMARY KEY ("IDX")  ) ;